theme:minima
title: bbinc
author: Beautiful Bridgette
email: beautifulbridgetteinc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  portfolio and detail site for bbinc.consulting gallery contact info chedule of availability 

# social links
twitter_username: beautofulbridgette
github_username:  beautifulbridgette

show_excerpts: false # set to false to remove excerpts on the homepage
